**❓ What is Pandas**

Pandas is a Python library used for loading, cleaning, and analyzing data. It provides easy to use tools like Series and DataFrames for working with structured datasets.

**⚙️ Why Pandas is Important in Machine Learning**

Pandas is the **go-to library for data manipulation and analysis** in Machine Learning.  
It is built on top of NumPy and provides easy-to-use data structures like **Series** and **DataFrame**.

**🔍 Why Pandas is Essential:**
- 📂 **Data Handling:** Load, clean, and preprocess real-world datasets (CSV, Excel, SQL, JSON).
- 🧭 **Data Exploration:** Understand your data — structure, missing values, correlations.
- ⚙️ **Integration with ML:** Works seamlessly with Scikit-Learn, NumPy, Matplotlib, and Seaborn.
- 📈 **Feature Engineering:** Create, transform, and select useful features for models.
- 🔢 **Efficient Operations:** Built on NumPy, so it’s fast and memory-efficient.

> 💡 *Pandas turns messy, raw data into clean, model-ready data.*

---

In [ ]:
%pip install -U -q pandas

In [1]:
import pandas as pd

#### Series (1D data)

In [4]:
s = pd.Series([10, 20, 30, 40, 50], name="Marks")
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

In [6]:
print(s[0])
print(s.mean())

10
30.0

### DataFram [2D]

In [8]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 35, 40, 45],
    "Score": [85, 90, 95, 80, 75]
}
print(data)
df = pd.DataFrame(data)
print(df)

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'], 'Age': [25, 30, 35, 40, 45], 'Score': [85, 90, 95, 80, 75]}
      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80
4      Eve   45     75

In [12]:
df.head()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80
4      Eve   45     75

#### Saving the Dataframe to a scv file

In [23]:
df.to_csv("../SupportingFiles/students.csv", index=False)

### Read Data From a CSV Files

In [ ]:
diabetes_df = pd.read_csv("../SupportingFiles/diabetes.csv")
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [21]:
diabetes_df.shape

(768, 9)

In [24]:
df

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80
4      Eve   45     75

In [28]:
df.head()

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80
4      Eve   45     75

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

### Selecting the data

In [30]:
# Single Coloumn
print(df["Name"])

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str

In [31]:
print(df[["Name", "Score"]])

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     95
3    David     80
4      Eve     75

In [32]:
# row selections  
print(df.iloc[1])  # This will raise an error because DataFrame does not support direct indexing like this.

Name     Bob
Age       30
Score     90
Name: 1, dtype: object

In [33]:
print(df.iloc[1])

Name     Bob
Age       30
Score     90
Name: 1, dtype: object

In [39]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Score": [85, 90, 95, 80, 75]
  }


sample_df = pd.DataFrame(data, index=["A", "B", "C", "D", "E"])

In [40]:
sample_df.head()

      Name  Score
A    Alice     85
B      Bob     90
C  Charlie     95
D    David     80
E      Eve     75

In [41]:
print(df.loc[1])  # This will work correctly to access the second row of the DataFrame.

Name     Bob
Age       30
Score     90
Name: 1, dtype: object

In [44]:
sample_df.iloc[1]

Name     Bob
Score     90
Name: B, dtype: object

### Filterting Data

In [45]:
hight_Scored_Data = df[df["Score"] > 80]
print(hight_Scored_Data)

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

### AddNew Coloumn

In [46]:
df["Passed"] = df["Score"] > 80
print(df)

      Name  Age  Score  Passed
0    Alice   25     85    True
1      Bob   30     90    True
2  Charlie   35     95    True
3    David   40     80   False
4      Eve   45     75   False

In [47]:
df["Scored_Percentage"] = df["Score"] / 100 * 100

In [48]:
df

      Name  Age  Score  Passed  Scored_Percentage
0    Alice   25     85    True               85.0
1      Bob   30     90    True               90.0
2  Charlie   35     95    True               95.0
3    David   40     80   False               80.0
4      Eve   45     75   False               75.0

In [50]:
df["city"] = ["NY", "LA", "SF", "CHI", "HOU"]

In [51]:
df

      Name  Age  Score  Passed  Scored_Percentage city
0    Alice   25     85    True               85.0   NY
1      Bob   30     90    True               90.0   LA
2  Charlie   35     95    True               95.0   SF
3    David   40     80   False               80.0  CHI
4      Eve   45     75   False               75.0  HOU

### Descriptive Stataistics

In [55]:
print("Average Score:", df["Score"].mean())
print("Max Score:", df["Score"].max())
print("Min Score:", df["Score"].min())

Average Score: 85.0
Max Score: 95
Min Score: 75

In [56]:
df.describe()

             Age      Score  Scored_Percentage
count   5.000000   5.000000           5.000000
mean   35.000000  85.000000          85.000000
std     7.905694   7.905694           7.905694
min    25.000000  75.000000          75.000000
25%    30.000000  80.000000          80.000000
50%    35.000000  85.000000          85.000000
75%    40.000000  90.000000          90.000000
max    45.000000  95.000000          95.000000

### Handling a Missing Data

In [66]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": [25, None, 35, 40, 45],
    "Score": [85, 90, None, 80, 75]
})

In [67]:
df2.head()

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   NaN   90.0
2  Charlie  35.0    NaN
3    David  40.0   80.0
4      NaN  45.0   75.0

In [68]:

df2.dropna(subset=["Name"], inplace=True)

In [69]:
df2

      Name   Age  Score
0    Alice  25.0   85.0
1      Bob   NaN   90.0
2  Charlie  35.0    NaN
3    David  40.0   80.0

In [70]:
df2.dropna(subset=["Score"], inplace=True)

In [72]:
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())

In [73]:
df2["Score"] = df2["Score"].fillna(df2["Score"].mean())

In [74]:
df2

    Name   Age  Score
0  Alice  25.0   85.0
1    Bob  32.5   90.0
3  David  40.0   80.0